### ISSUE TITLE
Combining Character at end of line problem.

### ISSUE THREAD

**Issue by richard-damon** [haney/python-ansel#9]
* ANSEL Codecs version: 0.1.1
* Python version: 3.9.5
* Operating System: Mac OS 11.3.1

### Description

I am reading in a GEDCOM 5.5 file, with the ANSEL character set. Some of the lines end with accent characters that become the ANSEL combining characters. In particular, I have data that ends in the Accent Grave character (00B4), which is converted to ANSEL E2 which gets converted to Unicode U+0301. It appears that the Codec, because Unicode puts combining characters after the base character, while ANSEL puts them before, moves the accent grave to after the end of line character so it is on the next line. (Actually, I think the file is using \r\n as it ends up on a line of its own)

It would seem better if before the Codec swapped the characters it first checked that the character was of the right class to do have this make sense, or at least check for control characters.

**Comment by haney** [comment]
@richard-damon Thank you for the bug report. I'd like to verify that I'm able to reproduce the problem that you reported. Could you provide a copy of the GEDCOM file you're attempting to parse, or a similar file that reproduces the problem?

**Comment by richard-damon** [comment]
[Test.txt](https://github.com/haney/python-ansel/files/6490763/Test.txt)

Trimmed it down to one test case with the issue and renamed the file to have the system let me upload it.

**Comment by richard-damon** [comment]
Looking at things a bit closer, It looks like the program generating the GEDCOM isn't always doing this right, as it will place the Accent Grave (U+00B4) into the file as the ANSEL character 0xE2 which is a non-spacing Accent Grave, and doesn't add the needed space after it. In this case, the absence of the space doesn't really violate the ANSEL spec, as what follows is a carriage return, so the non-spacing isn't really an issue. 

A second case where the conversion seems off is if the character is at the very end of a string, as then the character is just converted, but it will now attach itself to the previous character (since it wasn't moved past a character to attach to).

My guess is perhaps the simplest fix would be to detect these two similar cases (being at the end of a line/string) and add a space before the character (and not swapping with the end of line character).

**Comment by haney** [comment]
That's consistent with my take as well. The ANSEL specification indicates that combining characters should be treated as non-spacing characters, i.e. they do not advance the output device. This essentially results in the following character super-imposing itself on the non-spacing character. In the case where there isn't a following character (i.e. end of file or end of line), the combining character has still be written to the output device, it is just that a spacing character was not written. This is equivalent to writing a space (which advances the output device, without modifying what's currently present).

Adding a space when a control character (or end of file) is encountered seems to preserve the original intent around how combining characters in ANSEL were meant to be handled.
